notion:
  database_id: "357c8f4b4994818ca5a3eb2791d0f6cc"

fields:
  coin: "Название"
  orders: "Текущая прибыль [+] [F]"
  active: "Активных ордеров [R]"
  profit_all: "Текущая прибыль [F]"

tracking:
  min_profit_change: 10
  check_interval_minutes: 3

stats:
  database_id: ""
  name_field: "Название"
  value_field: "Статистика"
