notion:
  database_id: "357c8f4b4994818ca5a3eb2791d0f6cc"

fields:
  coin: "Название"
  orders: "Текущая прибыль [+] [F]"
  active: "Активных ордеров [R]"
  profit_all: "Текущая прибыль [F]"

tracking:
  profit_step: 5
  check_interval_minutes: 3

stats:
  database_id: "357c8f4b499481bbb852d7d80d7ad363"
  name_field: "Name"
  value_field: "Итог"
