notion:
  habits_db_id: "365c8f4b499480c0a2dad34b5817f704"
  schedule_db_id: "367c8f4b4994806784f1f79cc735a22b"

habits_fields:
  name: "Название"
  days_without: "Эффективность [F]"
  counter: "Срок [P]"

schedule_fields:
  name: "Название"
  time: "Время"

habits:
  - "Курение"
  - "Алкоголь"
  - "Газировка"
  - "Кофе"
  - "Переедание"
  - "Мучное"
  - "Сахар"
  - "Сладкое"
