notion:
  habits_db_id: "365c8f4b499480c0a2dad34b5817f704"
  schedule_db_id: ""

habits_fields:
  name: "Название"
  days_without: "Эффективность [F]"
  counter: "Срок [P]"

schedule_fields:
  name: "Напоминание"
  time: "Время"

habits:
  - "Без курения"
  - "Без алкоголя"
  - "Без газировки"
  - "Без кофе"
  - "Без сладостей"
  - "Прогулка"
  - "Без переедания"
  - "Велотренировка"
  - "Без рутсама"
  - "Без мучного"
  - "Без сахара"
